---
language: python
services: docker
env:
  global:
    - ROLE_NAME: repo-epel
install:
  - pip install molecule yamllint ansible-lint docker
before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME $ROLE_NAME
  - cd $ROLE_NAME
script:
  - molecule test
